### ISSUE TITLE
ToolTranslate - Broken responsive behaviour

### ISSUE THREAD

**Issue by sylvainlg** [dataesr/react-dsfr#315]
If the screen is about 1000px wide, the translation menu is cut off. Is it possible to put it on the other side (left in LTR and right in RTL)?

![image](https://user-images.githubusercontent.com/568835/205583921-c8e1df8c-14c8-413e-8e58-69cd1447ed81.png)

---

This can be done by adding the `left: 0;` (RTL), but is not automatically handled.

```css
@media (min-width: 62em)
.fr-translate__menu {
    margin: -0.25rem -1rem 0;
    top: calc(100% - 1rem);
    left: 0;
}
```

**Comment by sylvainlg** [comment]
I manage to fix it with : 

```css
@media (min-width: 62em) {

    [dir="ltr"] .fr-translate__menu {
        right: 0;
    }
    [dir="rtl"] .fr-translate__menu {
        left: 0;
    }
}
```
