### ISSUE TITLE
La croix est doublée sur le bouton de fermeture d'une modale

### ISSUE THREAD

**Issue by jerem1508** [dataesr/react-dsfr#330]
Le ds-fr ajoute en "after" une icone "x" sur le bouton de fermeture

Je propose de supprimer l'ajout automatique de la croix sur le before dans le fichier `react-dsfr/src/style/reset-dsfr.css` ligne 105

```css
.fr-notice button.fr-btn--close:before,
.fr-link--close:before {
  content: '\eb99' !important;
} 
```
devient : 
```css
.fr-notice button.fr-btn--close:before{
  content: '\eb99' !important;
}
```
